version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forest-bd-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/forest_db
      - NODE_ENV=development
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - forest-network
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forest-bd-frontend
    environment:
      - NEXT_PUBLIC_GRAPHQL_URL=http://localhost:3001/graphql
      # Décommente et configure si tu es derrière un proxy
      #- HTTP_PROXY=http://user:pass@proxy:port
      #- HTTPS_PROXY=http://user:pass@proxy:port
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - forest-network
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
      - /app/.next

  db:
    image: postgis/postgis:14-3.3
    container_name: forest-bd-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forest_db
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - forest-network
    restart: unless-stopped

volumes:
  database_data:
  frontend_node_modules:
  backend_node_modules:

networks:
  forest-network:
    driver: bridge
